version: '3'
services: 
  db:
    image: mongo:latest
    container_name: vid-db
    ports:
      - "4002:27017"
    restart: always
  storage:
    image: vid-storage
    build:
      context: ./storage
      dockerfile: Dockerfile
    container_name: vid-storage
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=bsmswd
      - STORAGE_ACCESS_KEY=aJnO0CO4MYJpxoijrjoR51eNfjAldvAVLtK+cW86Lc1p3WqhkPegJczLDTeFxuosOr+NCFJbMi4F+dYSGdNF1w==
    restart: "no"
  video-streamer:
    image: video-streamer
    build:
      context: ./video-streamer
      dockerfile: Dockerfile
    container_name: video-streamer
    ports:
      - "4000:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=vid-storage
      - VIDEO_STORAGE_PORT=80
      - DBHOST=mongodb://vid-db:27017
      - DBNAME=video-streaming
    restart: "no"